version: "3.9"

services:
    llm-router:
        image: llm-router-server:latest
        container_name: llm-router-container
        command: tail -f /dev/null
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/kuo/max:/app
        working_dir: /app
        ports:
            - "8887:8887"
            - "5000:5000"
        deploy:
            resources:
                reservations:    
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        restart: unless-stopped
